### ISSUE TITLE
Cannot download the sample dataset

### ISSUE THREAD

**Issue by Minzhao1995** [Ram81/habitat-web#1]
Hi,

Thanks for your inspiring work. 

During the installation of habitat-web, I can not download the sample dataset. It seems that the link is incorrect.

Thank you!

**Comment by Ram81** [comment]
Hi @Minzhao1995 , thanks for pointing out the issue with the sample dataset. We are working on fixing the broken link. I'll let you know once we have the dataset up.

**Comment by Ram81** [comment]
Hi @Minzhao1995, I have fixed the broken link. Let me know if you face any issues with the download

**Comment by Minzhao1995** [comment]
Hi, thanks for your quick reply. I can download it now.
