### ISSUE TITLE
Cannot load scene

### ISSUE THREAD

**Issue by Minzhao1995** [Ram81/habitat-web#2]
Hi,

After following instructions of standalone application, I browsed to ObjectNav task and got the following on my browser and terminal respectively. I can not interact with the environment. 

Is it because the data path is incorrect? I placed the data under "habitat-web/build_js/task/habitat_web_app/data/".

Thanks!

![Screenshot from 2022-06-16 20-48-48](https://user-images.githubusercontent.com/13643627/174074547-767b2754-efaf-4b82-b639-49f82450e842.png)

![Screenshot from 2022-06-16 20-48-08](https://user-images.githubusercontent.com/13643627/174074504-6f26db15-b76b-4323-84c8-504d7fe619b7.png)

**Comment by Ram81** [comment]
Hi @Minzhao1995, yes this issue is likely due to an incorrect data path. The data should be placed at `habitat-web/task/data`. The build script automatically creates a symlink at `habitat-web/build_js/task/habitat_web_app/data/`. 

Can you also share the log on your browser console? It will have more details on what the exact error is.

**Comment by Minzhao1995** [comment]
Hi, thanks for your quick reply, I got this on my browser console.
![Screenshot from 2022-06-21 12-20-14](https://user-images.githubusercontent.com/13643627/174715723-66b28e67-b561-4385-a9bf-658ee229573b.png)

**Comment by Ram81** [comment]
Hi @Minzhao1995, please use the URLs in step #2 from [this section of the readme](https://github.com/Ram81/habitat-web#habitat-webgl-application-standalone-without-psiturk). It looks like you are using the incorrect URL to access the interface

**Comment by Minzhao1995** [comment]
Yes, after I use the right URL, it works! Thanks!
